//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilActivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTasks()
        {
            this.Registrations = new HashSet<Registrations>();
        }
    
        public int IDTask { get; set; }
        public int IDEvent { get; set; }
        public int IDSector { get; set; }
        public string TaskName { get; set; }
        public string TasksDescription { get; set; }
        public System.DateTime Deadline { get; set; }
        public int Points { get; set; }
        public string Status { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Sectors Sectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registrations> Registrations { get; set; }
    }
}
