//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilActivity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studDB : DbContext
    {
        public studDB()
            : base("name=studDB")
        {
        }
        private static studDB _context;
        public static studDB GetContext()
        {
            if (_context == null)
            {
                _context = new studDB();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
       
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<EventTasks> EventTasks { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Registrations> Registrations { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<StudentEventParticipation> StudentEventParticipation { get; set; }
        public virtual DbSet<StudentPositions> StudentPositions { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<StudentSectors> StudentSectors { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
