//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilActivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSectors
    {
        public int IDStudentSectors { get; set; }
        public int IDStudent { get; set; }
        public int IDSector { get; set; }
    
        public virtual Sectors Sectors { get; set; }
        public virtual Students Students { get; set; }
    }
}
