//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilActivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPositions
    {
        public int IDStudentPositions { get; set; }
        public int IDStudent { get; set; }
        public int IDPosition { get; set; }
        public int IDSector { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Positions Positions { get; set; }
        public virtual Sectors Sectors { get; set; }
        public virtual Students Students { get; set; }
    }
}
